# Generated by Django 5.0 on 2024-10-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=255)),
                ('esal', models.CharField(max_length=255)),
                ('eaddr', models.CharField(max_length=255)),
            ],
        ),
    ]
